[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pc_cr"
version = "0.1.0"
requires-python = "==3.10.14"
description = "A python package to detect and measure cracks using point clouds as described in Liu's thesis on Displacement and Damage Monitoring for Masonry Buildings Subjected to Ground Movements Induced by Underground Construction."
authors = [
    {name = "Yiyan Liu", email = "dimo.liu@gmail.com"},
    {name = "Harvey John Burd"},
    {name = "Sinan Acikgoz"}
]

dependencies = [
    "matplotlib==3.7.2",
    "numpy==1.25.1",
    "open3d==0.16.1",
    "pandas==2.0.3",
    "scikit-learn==1.3.0",
    "scipy==1.11.1",
    "shapely==2.0.1",
    "tqdm==4.65.0"
]

[project.scripts]
pc_cr_gui = "pc_cr.gui.gui:main"
